jwt:
  expires-time: 172800 # 48 hours
  key: "zjJSnw$13jskjx"
mysql:
  host: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  database: demo
  username: root
  password: ""
redis:
  database: 0
  addr: 127.0.0.1:6379
  password: ""
system:
  port: 8080
zap:
  format: console
  showline: true