mysql:
  host: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  database: demo
  username: root
  password: ""
jwt:
  expires-time: 172800 # 48 hours
  key: "zjJSnw$13jskjx"
zap:
  format: console
  showline: true