info:
  contact: {}
paths:
  /api/v1/Users/login:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"data":{"token":string},"msg":"user login succeed"}'
          schema:
            type: string
      summary: User login
      tags:
      - Users
  /api/v1/Users/register:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"data":{},"msg":"user register succeed"}'
          schema:
            type: string
      summary: Register new account
      tags:
      - Users
  /api/v1/todo:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"data":{"items":{}},"msg":"succeed"}'
          schema:
            type: string
      summary: Get all todo tasks
      tags:
      - Todo
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"data":{},"msg":"todo create succeed"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Create new todo task
      tags:
      - Todo
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"data":{},"msg":"todo update succeed"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Update an existing todo task
      tags:
      - Todo
  /api/v1/todo/:id:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"data":{"item":{}},"msg":"succeed"}'
          schema:
            type: string
      summary: Get one todo task
      tags:
      - Todo
  /api/v1/todo/by/:userID:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"status":200,"data":{"items":{}},"msg":"succeed"}'
          schema:
            type: string
      summary: Get all todo tasks of a specific user
      tags:
      - Todo
swagger: "2.0"
